services:
  mlog-mvc:
    image: mlog-mvc:2.2
    container_name: mlog-mvc
    ports:
      - "127.0.0.1:8080:8080"
    expose:
      - "8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - DB_TYPE=${DB_TYPE}
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
    volumes:
      - ./Data:/data:rw
      - /etc/localtime:/etc/localtime:ro
    restart: always

