version: '3'
services:
  glances:
    image: nicolargo/glances:latest
    restart: always
    pid: host
    network_mode: "host"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./glances.conf:/glances/conf/glances.conf"
    environment:
      - GLANCES_OPT=-w

