networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24

services:
  unbound:
    image: "klutchell/unbound"
    container_name: unbound
    restart: unless-stopped
    hostname: "unbound"
    volumes:
      - "./unbound:/opt/unbound/etc/unbound/"
    networks:
      private_network:
        ipv4_address: 192.168.100.200

  wg-easy:
    depends_on: [unbound, pihole]
    environment:
      - WG_HOST=dennysrv.duckdns.org
      - PASSWORD=Thanh@123
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.6.0.2
      - WG_DEFAULT_DNS=192.168.100.100
    image: ghcr.io/wg-easy/wg-easy:13
    container_name: wg-easy
    volumes:
      - .:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    dns:
      - 192.168.100.100
      - 192.168.100.200
    restart: unless-stopped
    networks:
      private_network:
        ipv4_address: 192.168.100.3

  pihole:
    depends_on: [unbound]
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    hostname: pihole
    dns:
      - 127.0.0.1
      - 192.168.100.200
    environment:
      TZ: "Asia/Hong_Kong"
      WEBPASSWORD: ""
      ServerIP: 192.168.100.100
      DNS1: 192.168.100.200
      DNS2: 192.168.100.200
    volumes:
      - "./etc-pihole/:/etc/pihole/"
      - "./etc-dnsmasq.d/:/etc/dnsmasq.d/"
    cap_add:
      - NET_ADMIN
    networks:
      private_network:
        ipv4_address: 192.168.100.100
